// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/kouame-florent/axone-api/api/grpc/server"
	"github.com/kouame-florent/axone-api/internal/repo"
	"github.com/kouame-florent/axone-api/internal/store"
	"github.com/kouame-florent/axone-api/internal/svc"
)

// Injectors from wire.go:

func InitializeNewAxoneServer() *server.AxoneServer {
	db := store.NewDB()
	ticketRepo := repo.NewTicketRepo(db)
	ticketSvc := svc.NewTicketSvc(ticketRepo)
	axoneServer := server.NewAxoneServer(ticketSvc)
	return axoneServer
}
